### ISSUE TITLE
Using SRID 4326 in vector-datasource

### ISSUE THREAD

**Issue by dimon777** [mapzen/vector-datasource#107]
Is it possible to use SRID 4326 in vector-datasource? I understand I need to load the data into Postgis with SRID 4326, but what about querying the data? Should I change queries/*.pgsql files accordingly or there is more to accomplish this? My goal is to use an unprojected SRID in the database and project on the fly either at the application or at a client level. I don't want to use 900913 in the database, I'd like to store unprojected data in PostGis. And another question: what are the drawbacks with this approach?

Thanks!

**Comment by rmarianski** [comment]
It should be possible, but I haven't tried it so I'm not sure what the extent of the changes will be.

I expect that you shouldn't have to change the query files themselves, but the sql generation logic [1]. If the data is in 4326, you'll need to ensure that the bounds that are used in the query are in latlong instead of mercator coordinates. The other bit to keep in mind is that the formatters expect their data to be in a particular projection. The json/topojson formats expect latlong, and the opensciencemap/mvt formats expect the input to be in mercator.

[1] https://github.com/mapzen/TileStache/blob/9ddf505701c517efed56f7728e07e19bf17f9843/TileStache/Goodies/VecTiles/server.py#L500
