### ISSUE TITLE
Cross-Origin Request Blocked when serving static and dynamic content

### ISSUE THREAD

**Issue by dimon777** [mapzen/vector-datasource#110]
Hi All,

I'm trying to use simple webpage using vector-datasource, and there is a CORS issue even when my start page is loaded from the same host. I'm not sure if it is port number (since I use another web server to serve the static content). It would be great if documentation describes on how to configure Tilestache and/or werkzeug on how to serve both static and dynamic vector datasource content and route it properly.

This is what FF console prints:

uncaught exception: [object XMLHttpRequest] <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://myserver:8080/all/2/1/2.json. This can be fixed by moving the resource to the same domain or enabling CORS.

Thanks!

**Comment by rmarianski** [comment]
It's a per layer configuration option in the tilestache config: `allowed origin`. We set it to `*` for all layers.

This option itself is documented in the tilestache documentation:

http://tilestache.org/doc/

It's probably worth mentioning explicitly on the wiki page here though, because I think it's a common issue. If you agree, would you like to add it into the wiki where you think it's appropriate?

**Comment by dimon777** [comment]
Hi Robert,

I agree 100% ! I'm not sure I can edit wiki though :)

**Comment by rmarianski** [comment]
Thanks!
