### ISSUE TITLE
Add network attributes to road, transit lines

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#121]
We kind of have this in the ref attribute on roads now, but it's not normalized (and the network attribute on the road's route relation is, more often than not).

We need this for:
1. Road shields
2. Improve road connectivity based on highway designation, not just road surface / width classification.

For instance: US 101 goes thru San Francisco, but for 1/2 it's length thru the northern part of the city it's shown only as highway:primary and kind:major_road. The southern 1/2 is marked highway:motorway and kind:highway.

For the road shields it seems like the network attribute is very useful.

To improve road connectivity we might be able to override the kind to show as highway?

**Comment by nvkelso** [comment]
For **road shields**, do we start exporting: tags->'network' as network?

Looks like we do a little **connectivity** testing like this for US Interstates already:
https://github.com/mapzen/vector-datasource/blob/master/data/functions.sql#L96

Could add network_val='US:US' and see where that gets us?

**Comment by rmarianski** [comment]
We already do include the `network` attribute on road features, like you just mentioned. How about changing the query to instead of querying on the `network` tag, instead include `type='route' and route='road'` features starting at z9. And when determining the `kind`, we can identify these relations as `highway`. We'll probably end up returning back duplicate geometries in these cases though, one for the underlying way and another for the relation, but maybe that's what we want to do?

This looks to be the relevant openstreetmap wiki page:

http://wiki.openstreetmap.org/wiki/Interstate_Highway_relations

**Comment by nvkelso** [comment]
Let's try to avoid duplicating line work (lifework, thanks autocorrect). Should we limit this to adding the network_val='US:US' test (like we do now for US Interstates)?

**Comment by rmarianski** [comment]
The duplicate geometries come from including both the ways and the relations. It already started happening when we included `network=US:I` features.

I would expect that querying on type/route would yield more results because according to the wiki page there are more network values besides `US:I` and `US:US`. I'm assuming we would want to include those as well.

**Comment by rmarianski** [comment]
Should we add in the additional relation features for now, and consider how to remove any duplication in the future?

**Comment by meetar** [comment]
Another test case of relation/feature property conflict: the Brooklyn-Battery connection is a relation (https://www.openstreetmap.org/relation/1860086), much of which is a tunnel (https://www.openstreetmap.org/way/5681925) – the roads layer currently includes both features, with the tunnel section properly marked as `is_tunnel : yes` but the whole relation marked as `is_tunnel: no`.

**Comment by nvkelso** [comment]
For:

> 2. Improve road connectivity based on highway designation, not just road surface / width classification.

We are doing this now in the Tangram scene file by testing the presence of the ref, and that's working fine. So we should focus work here on (1) alone.

**Comment by zerebubuth** [comment]
I think we talked about this, but I've now forgotten: do we want to overwrite any existing network tag on the way (there aren't many of them) with the result from the relation? Also, do we want to restrict looking up networks to non-minor roads (e.g: tertiary & above) and railways?

**Comment by nvkelso** [comment]
> do we want to overwrite any existing network tag on the way (there aren't many of them) with the result from the relation? 

Yes, overwrite the way's network value with the relation's network value.

> do we want to restrict looking up networks to non-minor roads (e.g: tertiary & above) and railways?

Yes (avoid doing this for minor roads)

**Comment by nvkelso** [comment]
Fixed in #170.
