### ISSUE TITLE
Suppress parking landuse labels until zoom 17

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#139]
Previously in #126 we suppress parking POIs until zoom 17. Turns out some of these are landuse labels (from relation AOIs) and we need to do this for the other data type, too.

**Comment by rmarianski** [comment]
The current landuse filter is completely based on area, and not the "types" of landuse features. The shortest step to take here now is to have these features be filtered out at the transform layer based on zoom, but longer term it would be better to transition the landuse filter function to be based on zoom level too, like the one for pois. In other words, instead of returning a boolean that represents whether to include the feature or not, the function can return back an integer that corresponds with the zoom level to start including it in.

**Comment by rmarianski** [comment]
Follow up question, do we want to just filter it out from the labels layer and leave it in the landuse one? I'm thinking that it would be filtered out of both to keep them consistent.

**Comment by nvkelso** [comment]
The layer the feature is represented in (POIs or Landuse Labels) doesn't matter and shouldn't be changed at this time. But the zoom clamp we applied to parking areas in POIs also needs to be applied to Landuse Labels (so the isolated P parking icons we see on the map now at zoomed out city zooms are also suppressed to zoom 17).

Yeah, long term we want to support the kind (type) based default min_zoom ranges in addition to the current area test in the Landuse layers. 

We should leave the features in the Landuse layer (only the area test), adding the kind test only for the Landuse-Labels layer.

**Comment by rmarianski** [comment]
Yea, I wasn't suggesting moving the layer for certain features. I was just trying to point out that for the pois layer we have the notion of different features appearing at different zoom levels. For landuse we don't at the moment. Sorry for any confusion!

If we want to keep those features in the landuse layer and only trim it from the landuse_labels layer, I think it's better to leave things the way they are for now, and just update the query used for landuse_labels to also filter out parking, ie `amenity != 'parking'` for z < 17.

**Comment by nvkelso** [comment]
Agree, your change works.
