### ISSUE TITLE
Add explicate building labels

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#226]
Like we do for Landuse labels now, we need a canonical label centroid for buildings.

This is to address the multiple duplicate building labels we're seeing today. Here's an example from @bcamper in NYC:

![screen shot 2015-09-17 at 6 50 49 pm](https://cloud.githubusercontent.com/assets/853051/9995925/8161448a-6039-11e5-87df-08f00e4ad259.png)

**Comment by bcamper** [comment]
Turns out one of those is actually an additional POI label (note one is not italic)... that's also something tricky to keep in mind here. Do we try at all to "de-dupe" cases where a POI appears in building polygon of the same name? That could be problematic as well since there are legit use cases for both.

**Comment by nvkelso** [comment]
Success! 

**Before:**
<img width="967" alt="screen shot 2015-10-01 at 18 00 37" src="https://cloud.githubusercontent.com/assets/853051/10237455/797ef7d2-6866-11e5-852c-b22080622de3.png">


**After:**
<img width="983" alt="screen shot 2015-10-01 at 18 00 54" src="https://cloud.githubusercontent.com/assets/853051/10237457/7d0ed05c-6866-11e5-971d-23595273e8a4.png">
