### ISSUE TITLE
The population field in the places layer is a string

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#230]
For the `places` layer, instead of returning back the population as a string, we should coerce to an integer in a transform. This would also simplify the sort function.

**Comment by nvkelso** [comment]
+1

**Comment by nvkelso** [comment]
Verified these are ints now instead of strings:
http://vector.mapzen.com/osm/all/11/328/793.topojson?api_key=vector-tiles-HqUVidw
versus prod:
http://vector.dev.mapzen.com/osm/all/11/328/793.topojson

http://vector.mapzen.com/osm/all/7/20/49.topojson?api_key=vector-tiles-HqUVidw
versus prod:
http://vector.dev.mapzen.com/osm/all/7/20/49.topojson
