### ISSUE TITLE
Water polygons sometimes missing boundary line

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#303]
Lake Merced in SF shows a water boundary line around one of the two lakes, but both lakes should have a boundary. 

Might be related to MultiPolygons (the missing boundary is from a MultiPolygon)?

![screen shot 2015-10-12 at 15 35 50](https://cloud.githubusercontent.com/assets/853051/10440799/41265fbc-70f7-11e5-914a-0a2f7cfead9c.png)

![screen shot 2015-10-12 at 15 36 42](https://cloud.githubusercontent.com/assets/853051/10440800/41277226-70f7-11e5-8531-201fa56686d4.png)

![screen shot 2015-10-12 at 15 36 51](https://cloud.githubusercontent.com/assets/853051/10440798/410d885c-70f7-11e5-9a6e-1545b8b5be1e.png)

**Comment by nvkelso** [comment]
Seeing similar lack of water boundary features south of Washington DC around: 12/38.6837/-77.1095. Most look to be tagged `riverbank` and not part of relations.

**Comment by zerebubuth** [comment]
## Lake Merced

This appears to be happening because the geometry is duplicated as part of the import: Osm2pgsql usually deleted "superseded" member geometries of relations, but will keep a constituent member geometry of a relation in the database if it has tags which aren't present on the relation. That's happening here, as the largest part of Lake Merced is tagged with a `wikipedia` tag.

I have a patch which fixes this by unioning all geometries together before separating each feature's boundaries. Unfortunately, it's about 3x slower than the existing implementation and I can't think of a way to speed it up, as most of the time is spent in the `unary_union` operation. Given that the exterior boundaries is already one of the slowest operations we perform on a tile, this means it could make the whole process about 2-3x slower.

Alternatives such as simply excluding relations (or non-relations) won't work, as water polygons are sometimes mapped as either, and constituent parts are generally superseded. What's the trade-off between getting it right and getting it fast?

@rmarianski can you think of anything I've missed / any other ideas worth trying?

## South of DC

@nvkelso, I can't find the area you mention - I've checked along from Pohick Bay to Gravelly Point - I can't see any missing boundaries. Could you point out a particular feature that's missing that I can check, please?

**Comment by rmarianski** [comment]
In this case would the issue be resolved if the `wikipedia` tag were placed on the relation? And would that be more correct to do anyway? Even so, I imagine that in the general case there are legitimate scenarios where constituent ways would have tags that won't exist on the relation. Do we have any insights into how prevalent these cases are?

In terms of speedups, I can try to take a look at the patch to see. But if you're already grouping the "related" features and only performing the `union` on those, I can't really think of speedups. Maybe if we aren't already using a spatial index, we could try that? Or a quick inline bbox test before calling `union` to filter out cases where they obviously wouldn't combine?

**Comment by nvkelso** [comment]
> Lake Merced in SF

That sounds slow enough to not do, and prefer the data fix (moving the Wikipedia tag onto the relation instead of the part). 

Is this type of tagging funk common enough that we need to protect against it in our code base, or do one-off fixes in the data (or create a medium sized list of places to go fix using a tasking tool)? Or do we change our import process? 

> South of DC

Tile:
http://vector.mapzen.com/osm/all/13/2339/3142.topojson?api_key=vector-tiles-HqUVidw

Ah, looks like this is a stylesheet issue where the {riverbank, boundary} combo is only rendering at zoom 14+ as a thin line (I was viewing it at zoom 13).

But why is the circled "A" area showing a water boundary line in the middle of the water (for both `ocean` and `riverbank`)? Is there a way to drop that?

![screen shot 2015-10-22 at 14 30 56](https://cloud.githubusercontent.com/assets/853051/10678909/1cd2fa64-78ca-11e5-8755-581f922cae48.png)

**Comment by zerebubuth** [comment]
> In this case would the issue be resolved if the wikipedia tag were placed on the relation?

Yes.

> And would that be more correct to do anyway? Even so, I imagine that in the general case there are legitimate scenarios where constituent ways would have tags that won't exist on the relation.

In this case, perhaps. The relation really ought to cover all the separate bodies of water which are called Lake Merced and have the `wikipedia` and `name` tags only on the relation. That would fix this case, but you're right that there may be others for which the tag on the way is legitimate and correct, so we need to handle this case.

> Do we have any insights into how prevalent these cases are?

Looks like there are 3,059 cases in North America, out of 3,129,464 landuse polygons, so about one in 1,000 - it's pretty rare, but it might be very obvious in some cases.

> But why is the circled "A" area showing a water boundary line in the middle of the water (for both ocean and riverbank)? Is there a way to drop that?

The `exterior_boundaries` is supposed to... but it turns out in this case that there's a very, very small gap between the ocean and the riverbank (about 1cm in Mercator coordinates). This gap isn't present in the OSM data, so it likely comes from numerical precision artefacts due to the different processing pipelines (osm2pgsql vs. osmcoastline + shp2pgsql). A 1cm error represents about 0.0000001% relative error (on the same order as float epsilon), so it could easily have come from either pipeline.

One way to fix this would be to buffer the geometries by ~1cm before unioning them, but that would make the process even slower than the 3x. One thing I'll try is to snap the coordinates to a 5cm grid and see if that helps. Another way would be to pin and manually edit the ocean shapefile, but that's pretty unpalatable from a maintenance point of view.

The "right" fix is to maintain the topology, as the ocean and riverbank correctly share nodes... but we can't implement that in the short term.

**Comment by zerebubuth** [comment]
> Is this type of tagging funk common enough that we need to protect against it in our code base, or do one-off fixes in the data (or create a medium sized list of places to go fix using a tasking tool)?

I think we'll need to protect against it in the code - in some instances having an extra tag on the member way will be correct. It's possible that we can hack around it... it just might be a little ugly.

> Or do we change our import process?

Ultimately, yes, I think that's the right answer. But not something we should try and do quickly - I'm sure we can fix this problem "good enough" in the short term.

**Comment by zerebubuth** [comment]
With mapzen/TileStache#76 and #326,

## Lake Merced

![lake_merced_z16_after](https://cloud.githubusercontent.com/assets/271360/10698884/2ba32a78-79ab-11e5-9a1f-e0b24acdf6fd.jpg)

## Indian Head

![indian_head_z14_after](https://cloud.githubusercontent.com/assets/271360/10698894/33ec3526-79ab-11e5-9719-3b1550c08fd7.jpg)

**Comment by nvkelso** [comment]
Visually checks out :+1: 

You mentioned before that one approach took 3x as long as the current method. How much longer do  changes in this PR take?

**Comment by zerebubuth** [comment]
For a pretty small sample, I'm seeing slowdowns of between 25-50% from the snapping, mostly. I'd prefer it to be quicker, but 25-50% slower is much better than 200% slower :wink:

**Comment by zerebubuth** [comment]
@nvkelso - are we okay with the 25-50% slower performance?

**Comment by nvkelso** [comment]
Yes, pending perf testing on `dev` before we take it to `prod`.

**Comment by nvkelso** [comment]
@rmarianski Can you please look into profiling tile generation speed impact of this change before we take it to prod?

**Comment by nvkelso** [comment]
Verified.
