### ISSUE TITLE
Update tilejson tiles url to contain api key

### ISSUE THREAD

**Issue by rmarianski** [mapzen/vector-datasource#311]
It's more clear to update the tiles url to reflect that an api key should get passed through. Refs https://github.com/mapzen/vector-datasource/issues/310

**Comment by g12n** [comment]
Great! I was quite confused about that one. Mayebe you could add the URL to rev documentation. I just remembered it because I had used it before.

**Comment by nvkelso** [comment]
@g12n We made a change on the `dev` server to accommodate this. Can you try that with your config and let us know if it works? 

```
http://vector.dev.mapzen.com/osm/tilejson/mapbox.json
```

Note: When I try it in Mapbox Studio 0.2.7 it doesn't work for me, but your mileage may vary?

**Comment by nvkelso** [comment]
From the Mapbox issue (651 inline above), it sounds like we're hitting a low default timeout limit in Mapbox Studio Classic because we're testing against our `dev` setup which (generally) slowly generates tiles on request instead of having them ready before request.

We should pre-generate a region of tiles and test again against that region. 

(When I retested just now I'm getting a `Server returned HTTP 503` in Mapbox Studio Classic.)

**Comment by nvkelso** [comment]
Verified it's all working now :)
