### ISSUE TITLE
Include WOF macrohoods, microhoods

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#337]
Is Midtown a `macrohood` or a `neighborhood`? WOF has a grouping neighborhood concept for more significant features. As the data is cleaned up, we should also include those features (and mark them `macrohood` instead of `neighborhood`). 

Related: WOF also tracks `microhoods` for small neighborhood parts. We probably don't want to include those in this patch.

**Comment by rmarianski** [comment]
I compared the [macrohoods](https://github.com/whosonfirst/whosonfirst-data/blob/master/meta/wof-macrohood-latest.csv) and [microhoods](https://github.com/whosonfirst/whosonfirst-data/blob/master/meta/wof-microhood-latest.csv) with the [neighbourhoods](https://github.com/whosonfirst/whosonfirst-data/blob/master/meta/wof-neighbourhood-latest.csv) csv. There are no common ids between the neighbourhoods file and the (micro|macro)hoods. Are these linked in any way? Maybe through the parent_id?

Additionally, the label lat/lng values are all 0 for the (micro|macro)hoods, which is what we are currently importing to use as the geometry position.

Tangentially, it looks like 0 values are coming back through the data, we might want to filter those out during import. It looks like all neighbourhoods do all have label positions though. Alternatively, we could have WOF generate empty strings instead of 0 values to signal whether a label position exists.

**Comment by nvkelso** [comment]
They should be linked via parent_id and general hierarchy.

On Mon, Oct 26, 2015 at 10:08 AM, Robert Marianski <notifications@github.com

**Comment by nvkelso** [comment]
File a bug against WOF/data for the missing label positions.

**Comment by rmarianski** [comment]
> They should be linked via parent_id and general hierarchy.

I guess this means that we'll need to fetch the raw neighbourhood data for each record to gain access to this?

> File a bug against WOF/data for the missing label positions.

https://github.com/whosonfirst/whosonfirst-data/issues/129

**Comment by nvkelso** [comment]
> I guess this means that we'll need to fetch the raw neighbourhood data for each record to gain access to this?

Yeah, parent_id doesn't specify the place type of the parent, we'd need more data (by either importing more meta files, or the actual records).

**Comment by nvkelso** [comment]
Verified BoCoCa and the SF microhoods.
