### ISSUE TITLE
Add importance indicator to WOF neighborhoods

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#338]
It's hard to tell if one neighborhood is more important than another and labels are crowding. We can use area as a rough proxy, and also number of contributing photos or some direct indicator from Who's On First like `min_zoom` / scale rank.

#14/37.7583/-122.4419

![screen shot 2015-10-26 at 09 17 17](https://cloud.githubusercontent.com/assets/853051/10734832/69d03066-7bc2-11e5-940c-d89a1cca674c.png)

**Comment by rmarianski** [comment]
We're only pulling down the meta file at the moment, so we're limited in terms of the information we have available to us. The bounding box is included there, and it should _mostly_ be able to serve as a proxy for calculating the area. The edge case would be a neighborhood that is a thin diagonal.

Or do you think that we'll need to gain access to the raw files themselves eventually anyway, in which case we should start going down that path sooner rather than later. Would we want to crawl the data every time we import? Or is there some sort of other api planned for this sort of thing? There are about 50k neighbourhoods at the moment.

**Comment by zerebubuth** [comment]
We can keep the hash column in the database as a "version" or ETag, so we only need to re-fetch those for which the meta file tells us the hash has changed. But still, it's a lot of extra work to pull those down, parse them, etc...

Is area a good enough indicator of importance to justify this? `misc:photo_sum` has been mentioned as an alternative, but does that have universal coverage?

**Comment by nvkelso** [comment]
Let's do `tile_rank` using photo counts from WOF/Quattroshapes and tie break based on area. Also include `area` in tile properties.

**Comment by nvkelso** [comment]
Are we inventing `scalerank: 12` on all these features? Is that a legacy from the OSM sourced neighborhoods?

**Comment by rmarianski** [comment]
> Are we inventing scalerank: 12 on all these features? Is that a legacy from the OSM sourced neighborhoods?

It is. I think it started coming from the ne dataset, and then we added some default values in a [transform](https://github.com/mapzen/TileStache/blob/dae48ddeca0164fba02c723bd0f932d9f94f9000/TileStache/Goodies/VecTiles/transform.py#L1136-L1194).

Should we put the new values calculated from the WOF values into this existing `scalerank` property _instead of_ making a new `tile_rank` attribute?

**Comment by nvkelso** [comment]
No, these new WOF features shouldn't get a `scalerank` property. Instead we should expose the `min_zoom` and `max_zoom` properties (sourced from `mz:min_zoom` and `mz:max_zoom), as well as a `is_aoi` (sourced from `mz:is_aoi`).

The `tile_rank` should be `kind_tile_rank` (pending other discussion in the station issue), and should be sorted first on `min_zoom` and then on `photos_sum`.

**Comment by nvkelso** [comment]
This tile doesn't make sense. All the features with `min_zoom` of 12 have a high `kind_tile_rank`, and features with `min_zoom` of 13 have a low `kind_tile_rank`. The opposite should be true.

* http://vector.dev.mapzen.com/osm/all/12/654/1583.topojson?api_key=vector-tiles-HqUVidw

This feature has a min_zoom of 13, but kind_tile_rank of 1. 

```
{
type: "Point",
properties: {
kind: "neighbourhood",
name: "Inner Richmond",
area: 2314979,
mz_n_photos: 53065,
max_zoom: 19,
kind_tile_rank: 1,
source: "whosonfirst",
min_zoom: 13,
id: 85865919
},
```
and 

```
{
type: "Point",
properties: {
kind: "neighbourhood",
name: "Richmond District",
area: 1623917,
mz_n_photos: 3082,
max_zoom: 13,
kind_tile_rank: 10,
source: "whosonfirst",
min_zoom: 12,
id: 85869003
},
```

**Comment by zerebubuth** [comment]
Hmm... I think this is because the ranking function assigns ranks in order; the first matching item gets 1, the second 2, etc... But I think we sometimes sort items in the layer so that the more important ones come _last_, which would be the opposite order.

For "painters algorithm", having more important things last is the right way to do it, but (IIRC) all drawing in Tangram is based on assigned z-index, which is independent of the order of the data in the tile. Also, when drawing things with collision/exclusion boxes (i.e: any icons or text), the things which are drawn _first_ are the most important.

We should make sure that we know, for each layer, which order is "correct", and that we have that documented somewhere, even if only as a comment in a YAML file. My thought is that we should order any "label" layer most-to-least, and any "polygon" or "line" layer as least-to-most, but we do have a bunch of layers where we mix labels and other features.

@nvkelso what do you think?

**Comment by rmarianski** [comment]
In this case it looks like I just never added the `min_zoom` to the `places` layer sort. I'll make a pr to address that.

**Comment by nvkelso** [comment]
Works now :)
