### ISSUE TITLE
Add landuse=winter_sports to landuse

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#343]
Pairing with: https://github.com/mapzen/vector-datasource/issues/342 to add ski routes to roads layer, we should mark the extend of the winter_sports areas by adding them to the landuse layer.

**Comment by zerebubuth** [comment]
After #430, it looks like this (without most of the labels - I really wasn't able to figure out why they aren't rendering):

## Lake Tahoe

Before:
![lake-tahoe-z11-before](https://cloud.githubusercontent.com/assets/271360/11665637/609db244-9de0-11e5-9836-705f52986e38.jpg)

After:
![lake-tahoe-z11-after](https://cloud.githubusercontent.com/assets/271360/11665642/64b7bf00-9de0-11e5-9728-16b367729552.jpg)

**Comment by zerebubuth** [comment]
It's worth noting that there are really very few of these (about 45 in North America), so perhaps something we can target with a Targeted Editing post? Pistes without an enclosing winter sports area?

**Comment by nvkelso** [comment]
@zerebubuth the new pistes features are in the roads layer, and we already calculate the landuse_kind for that layer, so it should be easy to make a Targeted Editing post highlighting the ones missing the landuse AOI, /cc @IndyHurt. The one thing to watch is making sure the landuse sort is sane (not 0 or 1, and probably above forest/wood) otherwise we won't consistently get that?

**Comment by nvkelso** [comment]
We're missing a sort key in the _landuse_sort_order definition in TileStache's tranform step. Let's set this on the server to `4` (so it's above forest and wood).

**Comment by zerebubuth** [comment]
I'm not sure that `order=4` is the right way to go. Many winter sports areas have forests within the grounds which quite nicely show the larger pistes. For example, with `order=4`, the whole ski area looks blank:

![heavenly-ski-area-z14-landuse-4](https://cloud.githubusercontent.com/assets/271360/11782042/5091c46e-a266-11e5-99a1-9b8e0ed48fd6.jpg)

Whereas, with `order=2`, a whole lot more detail is visible:

![heavenly-ski-area-z14-landuse-2](https://cloud.githubusercontent.com/assets/271360/11782051/5a6d6060-a266-11e5-968e-1233fcc8d5d0.jpg)

Unfortunately, the ski area itself almost disappears. Perhaps we need an `overlap`-style processing layer to add `landuse_parent_kind` so that we can display forests inside ski areas differently? Something to think about for #446.

**Comment by nvkelso** [comment]
Good point. In the stylesheet it defaults to `1` and I get mostly what you get for a value of `2`. Let's go with `2` as that is in with park (2) and still below forest (3).

I'm filtering "wood" and "forest" in the stylesheet so I get more of the `winter_sport` landuse area showing up (since it's not obscured) at zooms less than 14. Mostly we need to add the sort this landuse can partake in the road layer intercut.

**Comment by nvkelso** [comment]
Verified sort key.

**Comment by nvkelso** [comment]
@sensescape Candidate for another new icon `ski` / `winter_sport`.
