### ISSUE TITLE
Why aren't we seeing Grand Central Terminal as a station POI?

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/vector-datasource#349]
Why aren't we seeing Grand Central Terminal as a station POI? It does shows as a station on OSM.org. Note: this is a regression of sort from prod, where it was kind=yes in the buildings layer only, but in dev is missing from POIs and Buildings. Seems like a couple different active issues are colliding here, and reminds me of #282?

* https://www.openstreetmap.org/way/265947358
* http://vector.dev.mapzen.com/osm/all/15/9650/12315.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
Can you confirmed you tested against a recent version of Skin & Bones? That assumes there is **both** an `area` and a `label_position=yes` on features, otherwise they are culled from the selection. 

Talking more to Brett about this, Tangram **should** support selecting also on the feature's source $layer  (since pois, landuse, and building pois and label_positions are all thrown into 1 meta layer) , but that isn't fully implemented yet.

**Comment by nvkelso** [comment]
No longer a problem, I see them in v0.8 tiles on prod.

**Comment by nvkelso** [comment]
<img width="672" alt="screen shot 2016-03-11 at 10 37 16" src="https://cloud.githubusercontent.com/assets/853051/13711783/406175ae-e775-11e5-817f-9d1a2228eb83.png">
