### ISSUE TITLE
Add amenity:prison to landuse and POIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#370]
We're missing Rikers Island prison in NYC at #15/40.7886/-73.8804.

<img width="681" alt="screen shot 2015-11-02 at 22 46 03" src="https://cloud.githubusercontent.com/assets/853051/10902504/a94b0396-81b3-11e5-8a06-a33b38633f89.png">

**Comment by nvkelso** [comment]
Looks like prison is only being pulled in at zoom 16. That should be earlier for POIs, and landuse earlier earlier.

**Comment by zerebubuth** [comment]
# Riker's Island

Before, at z15, there was something showing up for me, but lacking an icon:

![rikers-island-z15-before](https://cloud.githubusercontent.com/assets/271360/12116668/6b34cdee-b3b3-11e5-89f9-084182bca12e.jpg)

After the changes, it's pretty much the same:

![rikers-island-z15-after](https://cloud.githubusercontent.com/assets/271360/12116669/75201890-b3b3-11e5-870c-accbb88eaee8.jpg)

But now the label is visible out to z13, after which it gets clipped due to having too small an area:

![rikers-island-z13-after](https://cloud.githubusercontent.com/assets/271360/12116681/89c45324-b3b3-11e5-8287-46b480f2f2e9.jpg)

It's present in the tiles out to zoom 10.

**Comment by nvkelso** [comment]
In prod I see the NYC Rikers Island prison in tiles at zoom 16+. I see the same thing in dev tiles (good), but I don't see this prison feature at zoom 15 or earlier tiles. Are we missing a db migration?

**Comment by zerebubuth** [comment]
Potentially related to: I forgot to [update fastly](https://github.com/mapzen/fastly-deployer/pull/9) after the last dev release. We'll have to check again after that gets fixed.

**Comment by nvkelso** [comment]
I see Rikers in NYC and I see San Quentin in bay area, verified.
