### ISSUE TITLE
MVT format broken?

### ISSUE THREAD

**Issue by andreynovikov** [mapzen/vector-datasource#375]
Have you changed something recently in mvt format? For instance in roads layer 'highway' and 'railway' properties are missing, but some new undocumented properties like 'landuse_kind' are introduced.

**Comment by zerebubuth** [comment]
Hi Andrey,

The vector tiles layer has been through quite a few changes in the past couple of months, and we have introduced some new properties such as `landuse_kind`. I just had a quick check and couldn't see missing properties, but I might not be looking in the right place. Could you give an example of a tile URL where you are seeing missing `highway` and `railway` properties, so that I can investigate, please?

Thanks!

**Comment by nvkelso** [comment]
Can't reproduce, please reopen if this is an issue again.
