### ISSUE TITLE
Automatic updates of WOF neighbourhood data

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#393]

**Comment by rmarianski** [comment]
If data "becomes" invalid somehow, like it starts missing a particular property that we depend on, or the type of data becomes invalid (it's a string where we expect a number), I'm thinking that it's better to not add/update it. This is the safest thing to do, because if we start missing certain required properties, like name or label position, there's not really much we could do to perform an update anyway. Does that sound like the right approach? This also means that if a feature "becomes" funky where it wasn't before, we aren't going to update it, and leave it in its pre-funky state. Of course once the funky state is removed we would update the feature again. At the moment we're not importing any features that are marked funky.

An alternative is to remove these feature from our model. Is that better to do? One edge case here that could make this dangerous would be if something like the label position property names changed. With a "remove policy" we would end up removing all features.

I recognize that both of these are pedantic cases, but I just wanted to communicate what the behavior would end up being so we're at least aware of it if it happens.

**Comment by zerebubuth** [comment]
> Does that sound like the right approach? This also means that if a feature "becomes" funky where it wasn't before, we aren't going to update it, and leave it in its pre-funky state.

I think there might be some corner-cases with this, for example if the new, funky state is also superseded then we might end up displaying the old, non-funky version along with the new, non-funky, superseding item.

I feel like the more that we do to try and curate the WOF data in our pipeline, the more trouble it's going to give us with weird edge cases, and the more time we'll end up spending to investigate why there's a discrepancy between what's in the spelunker and what's on the tiles.

Also, I feel like we'll get more people reporting issues against and fixing the WOF data if we show it "unvarnished". How we encourage people to do that from the tiles is another issue, though...

**Comment by rmarianski** [comment]
> I think there might be some corner-cases with this, for example if the new, funky state is also superseded then we might end up displaying the old, non-funky version along with the new, non-funky, superseding item.

Good catch on the `superseded_by` flag! It looks like we're currently only checking against that in the meta csv file. In the scenario where it becomes funky and superseded, we would then drop it, which I think is correct.

But, if it's not marked as superseded in the meta csv file, and marked as superseded in the json file, we would continue to try and process it, with the same "funky" edge cases. In this case I think we should check for the `superseded_by` flag in the raw json as well, and treat these cases as candidates for removal from our model.

> I feel like the more that we do to try and curate the WOF data in our pipeline, the more trouble it's going to give us with weird edge cases, and the more time we'll end up spending to investigate why there's a discrepancy between what's in the spelunker and what's on the tiles.

I agree as well, since we're starting to grow more and more of these scenarios. Part of the increased complexity though is that I've been trying to keep out records from our database that we would never want to show, like those that have been superseded or are funky. We could alternatively push this logic downstream into the queries. The update logic would then be a little bit simpler, at the expense of having more complex queries, which would possibly be a little slower too.

That being said, I still think that having this logic applied during writes is a better trade-off though.

Ultimately, imho it still feels like there ought to be something in between the raw WOF data and our process to import the data. Whether that's a service, library, pre-processed data that is clean and bundled by place type, or some other sort of interface, putting the logic in at that layer means that our import process could be simpler, implying that all other consumers of the data won't need to learn these smarts either. The option to pull down the raw data could still be there, but this could just present an alternate, simpler option, at least for some use cases.

**Comment by rmarianski** [comment]
Updated `superseded_by` handling done in https://github.com/mapzen/tilequeue/pull/48.
