### ISSUE TITLE
Large GeoJSON file 

### ISSUE THREAD

**Issue by musicformellons** [mapzen/vector-datasource#414]
I have a large GeoJSON file which contains a layer of specific pois all over the world. Currently the entire file is loaded even if the zoom is just on one country/ region/ city. What are my options to improve performance? 

I would think serving just the data relevant for the 'current viewport' would be a massive improvement, what is needed for that? To name some things I can imagine:
1) make vector tiles of the data so it is smaller
2) serve the layer from a server (needed to have the 'current viewport' behavior?!).

Are these feasible options to pursue? Any suggestions on how to approach this are very welcome.

**Comment by zerebubuth** [comment]
Making a single vector tile over the whole world would make the file itself smaller, but would still take up a similar amount of memory in the user's browser, I think. So it sounds like a better thing would be to generate a series of static tiles, perhaps at a single zoom level, and host them on a website or from S3 or something similar.

It looks like [TileStache](http://tilestache.org/) might be able to do something like that. There's an example in this [mailing list thread](https://groups.google.com/forum/#!topic/tilestache/RYZqssYzyQk) with a config for producing a single tile, so that should be easy to extend to all tiles. Then you should be able to point Leaflet or whatever you're using client-side to the static tiles and load them on the fly.

Sorry I couldn't be more helpful, but I hope that's useful info.

**Comment by musicformellons** [comment]
Ok, so sounds like I am headed in the right direction. Thanks.
