### ISSUE TITLE
Normalize openstreetmap sources (maybe others)

### ISSUE THREAD

**Issue by tallytalwar** [mapzen/vector-datasource#503]
Example tile: http://vector.mapzen.com/osm/all/17/38587/49285.json

OSM sources referred in this tile: `openstreetmap`, `openstreetmap.org`, `openstreetmapdata.com`. These can be normalized to either `osm` or `openstreetmap`.

Possible there are other combinations which I missed.

**Comment by rmarianski** [comment]
The possiblities for `source`:

```
'naturalearthdata.com' AS source,
'openstreetmap' AS source,
'openstreetmapdata.com' AS source,
'openstreetmap.org' AS source,
'whosonfirst' AS source,
```

We had a discussion earlier where I think we decided that it was important to distinguish data derived from osm and osm itself, namely we wanted to keep the `openstreetmapdata.com` and `openstreetmap.org` sources separate.

I suggest we normalize `openstreetmap` -> `openstreetmap.org`, and because now they are all domains, `whosonfirst` -> `whosonfirst.mapzen.com`:

```
'naturalearthdata.com' AS source,
'openstreetmapdata.com' AS source,
'openstreetmap.org' AS source,
'whosonfirst.mapzen.com' AS source,
```

**Comment by nvkelso** [comment]
:+1:

**Comment by nvkelso** [comment]
This one has stylesheet impact – many city labels go missing as the scene file filters on `source: openstreetmap`, and that's now `openstreetmap.org` in tile data on dev. Not a problem, just needs coordination.

Another consideration is being consistent with the sources that Mapzen Search exports, which don't have full URL style (so `openstreetmap` instead).

**Comment by nvkelso** [comment]
Change itself is verified, but QA Complete label is blocked on stylesheet coordination and Mapzen consistency check.

**Comment by nvkelso** [comment]
Stylesheet coordination for Eraser Map / Bubble Wrap is done. Other stylesheets need updates. 

Mapzen consistency changes will take a long time, let's move on this now.
