### ISSUE TITLE
Duplicate geom points cause "arrows" to draw in Tangram

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#569]
* **What did you see?** "Arrows" on lines
* **What did you expect to see?** Clean lines
* **What map location are you having problems with?** http://tangrams.github.io/eraser-map/#16/26.5310/-81.7526
* **Screenshot?** 

![pasted image at 2016_03_04 11_58 am](https://cloud.githubusercontent.com/assets/853051/13544414/ae386128-e22a-11e5-9c68-5964f57003f2.png)

**Discussion:** _Mostly from @bcamper below:_

It happens when two line vertices collapse into the same spot. In the above example, (part of) the problem is duplicate line points / degenerate lines in the tiles, here's an example from 17885/27755/16.

```
id 69629000, geom: [[[2205,3104],[1849,2611]],[[1849,2611],[1849,2611],[1512,2143],[1512,2143]],[[1512,2143],[1448,2053],[1380,1958],[1120,1596],[980,1408]],[[980,1408],[980,1408],[504,740],[0,46]],[[980,1408],[980,1408]],[[980,1408],[1018,1499],[1028,1591],[1015,1677],[982,1758],[928,1827],[860,1876],[765,1916],[669,1934]],[[1334,2035],[1388,2054],[1433,2080],[1471,2105],[1512,2143]],[[1512,2143],[1512,2143]],[[1849,2611],[1849,2611]],[[1849,2611],[1878,2706],[1888,2803],[1873,2876],[1848,2932],[1809,3008],[1780,3030],[1780,3030]]]
```

here's a bogus line in there for instance: [[1849,2611],[1849,2611],[1512,2143],[1512,2143]]

Sometimes zoom 16 has the problems, but zoom 17 on prod fixes itself, but zoom 17 on dev continues the problem.

We think the lines are degenerate because they're getting quantized to have dupe points in both MVT and GeoJSON formats. BUT TopoJSON format looks ok (on both dev and prod, and in all cases it affects z16 but not z15 or z17)

* MVT: the coordinates are [0, 4096], so it's not surprising some points get duped
* GeoJSON: are we doing some kind of decimal place rounding? that could explain it

Brett speculates that it's working in TopoJSON because it has its own quantization/scaling scheme that adapts its precision.

**Comment by zerebubuth** [comment]
I've fixed the source of the duplicate points in the tile given as an example in mapzen/TileStache#126. Sadly, there are almost certainly other sources of duplicate points (although there is now a test to ensure we don't regress).

We have a lot of processing steps in making a tile, most of which are capable of introducing invalid, empty or degenerate features. Up to and including the final "formatting" stage, where features which are valid in MVT (quantized to 4096, mercator) won't be valid in TopoJSON (finer quantization, lat/lon). Further, it might be possible for formatted features to be valid, but then be quantized or reprojected in client libraries in such a way to make them invalid or degenerate.

I figure we can either add a post-formatting stage which reads the tile back and fixes or discards any invalid geometries, one for each format, or fix the issues at source as and when they pop up. Either way is going to be a lot of work.

**Comment by bcamper** [comment]
Agree it's a tricky issue across client and server. It's true that client-side processing could introduce issues either through quantization or other transforms (and this can occur in Tangram right now), and the tiles by definition can't really prevent that. But I do think it's reasonable goal for the server to provide valid geometries. Ensuring there are no consecutive duplicate points in lines or polygon rings would be a good step towards this IMO, even if there are other known + unknown cases where other degenerate geoms will get through. On the other hand this may not obviate the need for us to do similar client-side checking in Tangram, especially with user-provided data, etc.

FWIW TopoJSON is holding up better than MVT so far (e.g. spot-checking some of the issues we've seen), presumably because it adjusts its scaling factors based on the data, while MVT always samples to a 0-4096 integer resolution (with default extent anyway)?

The different effective resolution of the formats raises an interesting problem: previously the formats have simply been different containers for the same data, but if we remove invalid geometries, we will end up with cases where different formats actually have divergent data when decoded. This isn't necessarily critical, but complicates the mental model a bit too.

**Comment by zerebubuth** [comment]
> But I do think it's reasonable goal for the server to provide valid geometries.

For which definitions of valid, though? I think this needs to be written down, unambiguous and testable, otherwise we'll keep revisiting this issue.

> ... previously the formats have simply been different containers for the same data ...

I don't think two formats have ever been simply containers for the same data - the formats as we use them define the precision of the points, and so no two formats for the same tile contain the exact same data. Previously, we've included invalid geometry in all formats - sometimes the geometries which are invalid are different between two formats. The options appear to be: adopt a precision model (e.g: 4096 distinguishable points along the boundary) and a validity model (e.g: OGC when calculated on 4096-quantised mercator tiles) for all formats - or have some geometries only present in some formats.

I think the latter will be hugely confusing for us and our users, but the former would mean always using the "lowest common denominator" for precision, which would be a shame for formats which could support higher precision.

**Comment by bcamper** [comment]
Good points. I'd probably lean towards consistency at the expense of
flexibility (e.g. adopt a 4096 resolution and OGC validity) but agree this
needs to be thought through more.
