### ISSUE TITLE
Error while loading 10m_populated_places because of data value

### ISSUE THREAD

**Issue by batje** [mapzen/vector-datasource#577]
* **What did you see?**

While loading ne_10m_populated_places:

`

> addgeometrycolumn
>
> public.ne_10m_populated_places.the_geom SRID:900913 TYPE:POINT DIMS:2 
>(1 row)
>
>ERROR:  value too long for type character varying(41)
>CONTEXT:  COPY ne_10m_populated_places, line 4855, column ls_name: "Amundsen‰ÛÒScott South Pole Station (USA)"
>ERROR:  current transaction is aborted, commands ignored until end of transaction block
>ROLLBACK`

* **What did you expect to see?**

Success!

* **How did I solve it?**

`shp2pgsql -dIe -s 900913 -W Windows-1252 -g the_geom  ne_10m_populated_places-merc.shp ne_10m_populated_places | psql -U osm -d mydb `

Is a bit ugly, but it works.

**Comment by zerebubuth** [comment]
Thanks for reporting this! Looks like the encoding got messed up somewhere along the way. To give us a better chance of reproducing this, could you tell us what the encoding of your database is, please? You can see it by running:

```bash
psql -c "select pg_encoding_to_char(encoding) from pg_database where datname='mydb'" postgres
```

Strangely, in my database the encoding still looks wrong, but the length is reported as 41:

```
mapzen=# select ls_name from ne_10m_populated_places where ls_name like 'Amundsen%';
                  ls_name                  
-------------------------------------------
 Amundsen‰ÛÒScott South Pole Station (USA)
(1 row)

mapzen=# select length(ls_name) from ne_10m_populated_places where ls_name like 'Amundsen%';
 length 
--------
     41
(1 row)
```

@nvkelso - I notice this is the `-merc` shape. Is it possible that either one leg or the other of the load/dump was done without `-W Windows-1252` when it was transformed?

**Comment by batje** [comment]
I git cloned and installed yesterday, not quite sure where the data came from at all :-). and my database is SQL_ASCII (which 'happened' when I followed the instructions on a clean ubuntu 14.04.)
I initially used the script, so that used -W Windows-1252, then I tried UTF-8 and LATIN1.
Then I returned to Winblows and found the workaround.

**Comment by batje** [comment]
I implemented the workaround in the script (which does not fix the root cause). The script now finishes.
https://github.com/mapzen/vector-datasource/pull/578

**Comment by zerebubuth** [comment]
That data is part of a set of shapefiles we ship with the source code (e.g: `ne_10m_populated_places-merc.shp` comes, somewhat confusingly, from [places-naturalearth.zip](https://github.com/mapzen/vector-datasource/blob/master/data/places-naturalearth.zip)) and the ones with `-merc` suffixes originally come from [Natural Earth](http://www.naturalearthdata.com/) and have been projected from the original latlon to "Web Mercator" (a.k.a 900913).

I think the root of the problem might be that the database is in SQL_ASCII encoding. I know this means going back to the beginning, and I'm sorry that the original documentation didn't include this, but could you try `createdb -E UTF-8 mydb` instead of `createdb mydb` at the very beginning of the install instructions, please?

I have a bad feeling that other things will go wrong, particularly with loading OSM data with `osm2pgsql`, if the database isn't in UTF-8 encoding.

**Comment by batje** [comment]
OK, I updated the wiki. Thanks.
