### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by TGISer** [mapzen/vector-datasource#869]
tilequeue wof-process-neighbourhoods --config tilequeue-config.yaml

File "/usr/local/lib/python2.7/dist-packages/tilequeue-0.8.0-py2.7.egg/tilequeue/format/mvt.py", line 1, in <module>
    from mapbox_vector_tile.encoder import on_invalid_geometry_make_valid
ImportError: cannot import name on_invalid_geometry_make_valid

**Comment by zerebubuth** [comment]
It looks like this is caused by running an earlier version of `tilequeue` with a later version of `vector-datasource`. This is because we've made changes in the development ("master") branch of `vector-datasource` which requires corresponding changes in the development branch of `tilequeue`.

There are two ways to resolve this:

1. Use the tagged releases of `vector-datasource` - at this time, the latest is [v0.10.3](https://github.com/mapzen/vector-datasource/releases/tag/v0.10.3), and the release notes give the corresponding tagged releases of the dependencies to use. This is what we are currently running in production.
2. Use the development ("master") branches of `vector-datasource`, `tilequeue` and `tileserver`. The easiest way to do this is to `pip install -Ur vector-datasource/requirements.txt`. Please bear in mind that, as a development branch, there may be issues with the install, and the content of the tiles may not be as expected. Additionally, the WOF dump will not work (it's from a v0.10.3 database), so it will be necessary to either install WOF data from scratch, or run the migrations (`vector-datasource/data/migrations/run_migrations.sh`) after loading the dump, and possibly rolling back any l10n schema changes. There is, I'm sorry to say, very little documentation on this.

I recommend using the tagged release.

Please also see the [installation instructions](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) for more details.

**Comment by TGISer** [comment]
@zerebubuth 

thank you but v0.10.3 do not have "setup.py" in its root directory.

vector-datasource-0.10.3# python setup.py develop
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by zerebubuth** [comment]
Yes, v0.10.3 is before `vector-datasource` had any code in it. Instead, it has an extra dependency on the `integration-1` branch of our [TileStache fork](https://github.com/mapzen/TileStache). The current installation instructions I linked to are probably updated and won't work for that older version, sorry. You might have better luck following [an older revision of the instructions](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/ed1d7a53b54113a294ad8dcff750d6d4eff67a58).

**Comment by TGISer** [comment]
@zerebubuth 
Thank you for your reply!

I just want get the ,mvt data  and use it in android by offline model  how can i do it

**Comment by zerebubuth** [comment]
If you are happy to use the data which we serve through our [production API](https://mapzen.com/projects/vector-tiles/) then the easiest way is to [sign up](https://mapzen.com/developers/) for an API key, and download the area which interests you. All of our tiles can be [cached for offline use](https://mapzen.com/documentation/vector-tiles/api-keys-and-rate-limits/#caching). API keys are [rate-limited](https://mapzen.com/documentation/vector-tiles/api-keys-and-rate-limits/#rate-limits), so please pay attention to the amount of tiles you download. If you are using our [mobile SDK](https://mapzen.com/projects/mobile/) then you need not download any zoom levels higher than z16, as z17, 18 and higher tiles can be "over zoomed" from the z16 ones.

If you find that your download requirements are higher than can be supported through our rate-limited service, then you will probably want to generate vector tiles. This is, unfortunately, not yet an easy process. I would recommend persevering with `vector-datasource`, as this will provide a server that you can download as much as you want from.

Finally, if you want a different data set, or control over the details of the data downloaded, then I do (of course) recommend `vector-datasource`, but there are also alternatives:

* [MAPS.ME OMIM](https://github.com/mapsme/omim) is a mobile-native offline format and mapping SDK for iOS and Android. It doesn't generate MVT format tiles, but has its own format. I have no experience of using it personally, but I've used the Android app and it's very impressive.
* [Tilemaker](https://github.com/systemed/tilemaker) is a much more lightweight tile generating tool, which does not include a server, but should be fine for generating small areas of MVT tiles for offline use.

Hope that helps.

**Comment by TGISer** [comment]
@zerebubuth 
Thank you for your integrated suggestion.

I am sorry my english is not very good ,and i do not find the way.

How can i download your service data "Manhattan" mvt data for example and use it in android by offline model.

**Comment by rmarianski** [comment]
If I understand what you're trying to do, the [Tilemaker](https://github.com/systemed/tilemaker) approach that @zerebubuth recommended sounds like easiest approach for you. You can download the source pbf data for Manhattan from our [metro extracts](https://mapzen.com/data/metro-extracts/) and point Tilemaker at it to generate mvt tiles.

**Comment by TGISer** [comment]
@rmarianski   
thank you!
I can do it!
