### ISSUE TITLE
Building outlines do not contain their holes.

### ISSUE THREAD

**Issue by tillnagel** [mapzen/vector-datasource#88]
In the docs you state that polygons "represent building outlines" and include "building footprint at lower zoom levels, and individual building:part geometries [...] at higher zoom levels."

However, it seems it seems you do not use multi-polygons for buildings having outer and inner features, e.g. for inner court yards, etc. Any way of accessing these via your vector tiles?

Example: 
http://vector.mapzen.com/osm/buildings/18/140827/85996.json

**Comment by bcamper** [comment]
Hi Till -- the inner ring information is encoded in the vector tiles, but the confusion probably arises from how this data is stored natively in OSM. "Proper" GIS polygons have a concept of multiple rings in a single polygon (not multipolygon!), where the first ring is the outer ring, and subsequent rings are inner rings which are "cut out" of the outer one. A multipolygon is a separate concept, for spatially disjoint polygons (each of which can have its own outer and inner rings). 

Since OSM only has single-ring "ways", they have no native way of encoding multi-ring polygons, hence they use what they call "multipolygon" relations to encode this information. When this data is imported into postgis with osm2pgsql, those OSM multipolygon relations get converted into multi-ring polygons, or true multipolygons where they do not overlap. Some info in the [docs here](http://wiki.openstreetmap.org/wiki/Osm2pgsql).

In these vector tiles, those features are exposed as GeoJSON [polygons](http://geojson.org/geojson-spec.html#polygon) (which can have multiple rings, as in the building example you give) and disjoint [multipolygons](http://geojson.org/geojson-spec.html#multipolygon). You can see that building rendering correctly with inner courtyards here: http://tangrams.github.io/tangram/#mapzen,52.49877546805041,13.397671580314638,17

Hope that helps! I'm going to close this issue but feel free to follow up with any clarifications or issues here. Thanks.

**Comment by tillnagel** [comment]
Oh boy. Thanks very much for the explanation. I forgot about them. (It just seems so unsemantic.)

Anyway, glad to hear. Then it's simply a bug in my GeoJSON parser.
