### ISSUE TITLE
Error loading Tilestache config

### ISSUE THREAD

**Issue by miccferr** [mapzen/vector-datasource#89]
Hallo kind folks at Mapzen,

I'm trying to setup your fork of TileStache (in order to be able to serve my vector-tiles), but I'm running into the following error:  

````
Error loading Tilestache config:
Traceback (most recent call last):
  File "./scripts/tilestache-server.py", line 55, in <module>
    app = TileStache.WSGITileServer(config=options.file, autoreload=True)
  File "/Library/Python/2.7/site-packages/TileStache-1.49.11-py2.7.egg/TileStache/__init__.py", line 342, in __init__
    self.config = parseConfigfile(config)
  File "/Library/Python/2.7/site-packages/TileStache-1.49.11-py2.7.egg/TileStache/__init__.py", line 107, in parseConfigfile
    return Config.buildConfiguration(config_dict, dirpath)
  File "/Library/Python/2.7/site-packages/TileStache-1.49.11-py2.7.egg/TileStache/Config.py", line 217, in buildConfiguration
    config.layers[name] = _parseConfigfileLayer(layer_dict, config, dirpath)
  File "/Library/Python/2.7/site-packages/TileStache-1.49.11-py2.7.egg/TileStache/Config.py", line 447, in _parseConfigfileLayer
    layer.provider = _class(layer, **provider_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ignore_cached_sublayers'
````
What seems to cause the problem? 
If I simply run Tilestache without specifying any .cfg file it works just fine..
I also checked if I'm actually running your fork of Tilstache by exporting the folder, containing the clone of your github repo, to my PYTHONPATH.

Thanks in advance for your help!,
Cheers!

**Comment by rmarianski** [comment]
Are you running the `integration-1` branch of tilestache?

**Comment by miccferr** [comment]
yes of course ;)

**Comment by rmarianski** [comment]
The stack trace suggests that it's picking up the TileStache egg from your site packages, and not the one that you checked out. Maybe your PYTHONPATH isn't set correctly?

If you run this it should point to where you checked tilestache out, and not the egg location:

    python -c 'import TileStache; print TileStache.__file__'

**Comment by miccferr** [comment]
mmh..I imagined I might have messed up something with the PYTHONPATH.
Here's the output from inside the cloned Tilestache directory
`````
~/Progetti/vector-tiles/TileStache <integration-1> python -c 'import TileStache; print TileStache.__file__'
TileStache/__init__.py
`````  
And here's from outside 
`````
 ~/Progetti/vector-tiles python -c 'import TileStache; print TileStache.__file__'
/Library/Python/2.7/site-packages/TileStache-1.49.11-py2.7.egg/TileStache/__init__.pyc
``````
But when I'm running the command to start TileStache I'm doing it from within the TileStache directory, shouldn't it pick that one? (n00b question..)
````
./scripts/tilestache-server.py -c ../vector-datasource/tilestache.cfg 
````

**Comment by rmarianski** [comment]
If this isn't the case, I suggest setting the PYTHONPATH to an absolute path, ie:

    export PYTHONPATH=~/Progetti/vector-tiles/TileStache

To your question about picking up relative paths, I believe it's relative to the python file itself, and not the current directory. So if you copied tilestache-server.py up one directory and ran it from there, it would probably work, but I think it's best to use absolute paths to prevent confusion.

**Comment by miccferr** [comment]
nothing, I still get the same error..
I'll dig deeper though, and let you know the outcome.
Thanks for your help!

**Comment by jtsmn** [comment]
I ran into this too, and I'd forgotten to 
> pip install mapbox-vector-tile

I don't know if that'll help or not.

**Comment by xmarklabs** [comment]
Try executing this before you execute tilestache-server.py command

export LC_ALL="en_US.UTF-8"

It could be localization issue.

**Comment by NickXML** [comment]
I have a solution.  I'm a n00b at Tilestache, so bear with me. 

I was getting the same errors and had multiple issues. Most were stupid (you probably didn't make those ones), but it is now working.  I'll start with the least stupid error (and the one I think actually solved it).

The clue was found here:  

http://build-failed.blogspot.com/2012/03/custom-map-tiles-part-3-tilestache.html?showComment=1369922833284#c1652399450218963787

To cut a tedious story short, **you have more than one python "egg" (I think that is the term) installed and it's picking up a .cfg file from the wrong place.**  Yes, I know you are specifying the location in your command line, but it gets ignored somehow.

I'm on Ubuntu 14.04, so some of these paths may vary depending what OS you are using.

## Step One
Take a look here:
    ls /usr/local/lib/python2.7/dist-packages/

In my case, I had:
TileStache
TileStache-1.49.10.egg-info
TileStache-1.50.1-py2.7.egg

TileStache-1.50.1-py2.7.egg was the culprit.

## Step Two
Run:

    pip list

to see all of your installed Python packages.  Mine showed:

...
simplejson (3.6.5)
six (1.5.2)
ssh-import-id (3.21)
TileStache (1.50.1)
urllib3 (1.7.1)
Werkzeug (0.10.4)
...

Note that ONLY the TileStache 1.50 is listed.  This is **not** the Mapzen fork of Tilestache. It is an imposter that must be eradicated...

## Step Three
Now run:

    pip uninstall TileStache

Then, just to be cautious (this may not be necessary, again, I'm a bit of a n00b here):

    cd /to/your/mapzen/Tilestache/directory
    python setup.py install

And try re-running your ./scripts/tilestache-server.py -c etcetcetc command. Should now work.

## Other Dumb Things I Did
These almost certainly do not apply to you. 

1. I'm not sure my postgresql user had the right privileges. I did a bunch of "GRANT ALL PRIVILEGES ON ALL TABLES IN ..." for my DB user.
2. I had missed some instances of "user" and "database" in tilestache.cfg, so they were pointing to the wrong user/db


I'm now the proud owner of an (apparently) working mapzen fork of Tilestache.  Now I just need to figure out how to get it to server via Apache instead of werkzeug...

**Comment by NickXML** [comment]
P.s. Before I did any of this, I tried setting PYTHONPATH to an absolute path, but that didn't seem to solve the issue.

**Comment by rmarianski** [comment]
Thanks for the potential fixes all, and especially @NickXML for the detailed write-up.

@miccferr, does this help?

**Comment by miccferr** [comment]
@rmarianski yes! I was about to write a reply.  
Thanks to @NickXML now I have a beautiful working instance of Mapzen's Tilestache.  
I guess the error was, as suggested, that python was trying to summon a wrong egg of Tilestache. Thanks again everybody for your replies and help.  
Cheers!

**Comment by NickXML** [comment]
Glad it helped. Took quite a bit of google-whacking to figure out what was going on... the curse of knowing just enough to be dangerous ;-)
